---
- name: "Add nodes to required groups"
  hosts: storm-nodes
  connection: local
  gather_facts: False
  tasks:
    - name: "Add a maximum of 3 nodes to the zookeeper-nodes group"
      add_host:
        name: "{{ hostvars[item.1].inventory_hostname }}"
        ansible_host: "{{ hostvars[item.1].ansible_host|default(hostvars[item.1].ansible_ssh_host) }}"
        ansible_user: "{{ hostvars[item.1].ansible_user|default('root') }}"
        ansible_ssh_pass: "{{ hostvars[item.1].ansible_ssh_pass|default('') }}"
        ansible_become_user: root
        ansible_become_pass: "{{ hostvars[item.1].ansible_ssh_pass|default('') }}"
        id: "{{ item.0 + 1 }}"
        groups: zookeeper-nodes
      with_indexed_items: "{{ groups['storm-nodes']|sort|batch(3)|list|first }}"

    - name: "Add all cluster nodes to the storm-nodes group"
      add_host:
        name: "{{ hostvars[item.1].inventory_hostname }}"
        ansible_host: "{{ hostvars[item.1].ansible_host|default(hostvars[item.1].ansible_ssh_host) }}"
        ansible_user: "{{ hostvars[item.1].ansible_user|default('root') }}"
        ansible_ssh_pass: "{{ hostvars[item.1].ansible_ssh_pass|default('') }}"
        ansible_become_user: root
        ansible_become_pass: "{{ hostvars[item.1].ansible_ssh_pass|default('') }}"
        id: "{{ item.0 + 1 }}"
        groups: storm-nodes
      with_indexed_items: "{{ groups['storm-nodes']|sort }}"

- name: "Show debug info"
  hosts: storm-nodes
  become: yes
  tasks:
    - name: "Show Kafka nodes info"
      debug: var=hostvars[inventory_hostname]
      when: debug

- name: "Apply the common role to all nodes"
  hosts: storm-nodes
  become: yes
  roles:
    - common

- name: "Apply the zookeeper role to the Zookeeper nodes"
  hosts: zookeeper-nodes
  become: yes
  roles:
    - zookeeper

# see group vars. Control which componentd are deployed where
- name: "Apply the storm role to the Storm nodes"
  hosts: storm-nodes
  become: yes
  roles:
    - storm

- name: Ansible-Sample-TDD
  hosts: storm-nodes
  user: root
  roles:
    - storm
    - zookeeper
 
