# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://rm-bp1b8emy32l7ozf046o.mysql.rds.aliyuncs.com:3306/wamoli?useUnicode=true&characterEncoding=utf8&useSSL=false
        driverClassName: com.mysql.jdbc.Driver
        name:
        username: root
        password: admin@9578
#        password: Retail@2016#
    h2:
        console:
            enabled: false
    cache:
        jcache:
            config: ehcache.xml
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false

liquibase:
    contexts: dev

server:
    port: 8080

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        ehcache:
            maxBytesLocalHeap: 16M
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: 24cde48fb021366aa70dcd532871fcc3a22eba23
        authentication:
            jwt:
                secret: fa5e3e93a6ba8f90128a00cd93e8cae3d970fdea
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: Wamoli@localhost
        baseUrl: http://127.0.0.1:8080
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: Wamoli
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
    mybatis:
        mapperLocations: classpath*:com/distribution/wamoli/**/mapper/*Mapper.xml
        configLocation:  classpath:mybatis/SqlMapConfig.xml
        type-aliases-package: com.distribution.wamoli.**.domain
    wamoli:
        localSpace: f:/jar/
        attachPath: D:/webFile/goshop
#    cors: #By default CORS are not enabled. Uncomment to enable.allowed-origins
#        allowed-origins: "*"
#        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
#        allowed-headers: X-Requested-With
#        exposed-headers:
#        allow-credentials: true
#        max-age: 1800

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://jhipster.github.io/common-application-properties/
# ===================================================================

application:
