---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-application-deployment
  labels:
    deployment: web-application-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web-application
    spec:
      containers:
      - name: web-application-container
        image: katacoda/docker-http-server:latest
        ports:
        - name: http-port # must be no more than 15 characters
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-application-svc
  labels:
    svc: web-application-svc
spec:
  # type: NodePort
  # ports:
  # - port: 30080
  #   nodePort: 
  ports:
  - name: svc-port # must be no more than 15 characters
    port: 30080
    targetPort: http-port
  selector:
    app: web-application

  # Disable Walking across Backends
  #
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 100
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-application-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: web-application.kubernetes.example
    http:
      paths:
      - backend:
          serviceName: web-application-svc
          servicePort: svc-port

