# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://rm-bp1b8emy32l7ozf046o.mysql.rds.aliyuncs.com:3306/goshop?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: admin@9578
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
#    jpa:
#        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#        database: MYSQL
#        show-sql: false
#        properties:
#            hibernate.cache.use_second_level_cache: true
#            hibernate.cache.use_query_cache: false
#            hibernate.generate_statistics: false
#            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
#            hibernate.javax.cache.uri: ${spring.cache.jcache.config}
#            hibernate.cache.region.factory_class: com.distribution.wamoli.config.jcache.SpringCacheRegionFactory
    cache:
        jcache:
            config: ehcache.xml
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: true

liquibase:
    contexts: prod

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        ehcache:
            maxBytesLocalHeap: 256M
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: 24cde48fb021366aa70dcd532871fcc3a22eba23
        authentication:
            jwt:
                secret: fa5e3e93a6ba8f90128a00cd93e8cae3d970fdea
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: Wamoli@localhost
        baseUrl: http://my-server-url-to-change # Modify according to your server's URL
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: Wamoli
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
    mybatis:
        mapperLocations: classpath*:com/distribution/wamoli/**/mapper/*Mapper.xml
        configLocation:  classpath:mybatis/SqlMapConfig.xml
        type-aliases-package: com.distribution.wamoli.**.domain
    wamoli:
        localSpace: f:/jar/
        attachPath: f:/jar/

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://jhipster.github.io/common-application-properties/
# ===================================================================

application:
